language: java
jdk:
- oraclejdk11
jobs:
  include:
  - stage: deploy to heroku
    script: skip
  - stage: test production deploy
    script: curl https://yieldme-back.herokuapp.com
deploy:
  provider: heroku
  api_key:
    secure: $SECURE_KEY
  app: $APP
