language: java
jdk:
- oraclejdk11
jobs:
  include:
  - stage: deploy to heroku
    script: skip
  - stage: test production deploy
    script: curl https://yieldme-back.herokuapp.com
deploy:
  provider: heroku
  api_key:
    secure: njovqn1ZeLeL3nAeuQGQUfAuIrAVgLewzmgqFMOts3Innvlo12K6FR1dBsUVtrfrmFshFsRQDDMnCXlEMgxtAzQmhVjP/oRBOM6D80+VWq2wNkVYk0a8PSgr0czfyrLnsH/o0NLwvRW8E8ejMNLKICb7lf/Zw3GqZ92EazPI9Fu+XnPFd8NLmtxCCNmKYgXna4khx9mGUeO0UaKJ6luC+Bpmq7lSwMXMiUxd25ZMJSpB4zI0hFcmEdtsUHm8LVA6eHc7SxxQXJaSKhavsb29UGimpg9TB6/ddVxQY+QElvvFBIoL331Is+0Dna62+dHS4bQ5/iryaZz/UipLyQSSahYqFBh0CtzgNe2CLoQIPaePQNP8p4tIiGyVbNMP/jlRKZ9NSYUagO9vTp0kCgvtC6VT4wPMhUEtJb0n33ldePMkeV2h89LvAN5shQmtwlUUsp+1yLB019ip1vb5YYXLWHmWKpC3VDcDYLIJ/s2MrAzcv4AO4JDG1CD3bgnTp9Aep5RSTxUFWWyXTjHo2KA9XXzUjnD01zyEcAaoca8RO6uwbnPcQEHeZ1nPVLE15hN5WjWHC/Ljyec1m7jCiNrpnPRFa01hkJWk1GD6JKcCuDcgutJWrtS7B1EuEuUN9rszitIXe7iuWBLL1I05CLMuQH/h+pSc2aB7OlDngZMq0sA=
  app: "$APP"
