spring:
  profiles:
    active: local
  application:
    name: yield-me

security:
  jwt:
    token:
      secret-key: super-secret-key
      expire-length: 3600000 # 60 minutes duration by default: 60 minutes * 60 seconds * 1000 miliseconds

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  newPassword: Changes user's password
  me: Returns current user's data

ContributionsController:
  findAll: FindAll Contributions by user
  create: Creates contribution
  findOne: Find one specific contribution
  update: Update specific contribution
  patch: Patch specific contribution
  delete: Deletes specific contribution