spring:
  datasource:
    url: jdbc:mysql://us-cdbr-east-02.cleardb.com/heroku_954070ce9baddba?reconnect=true
    username: b075bb15cc03cf
    password: d2016445
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
  port: 8080 # This is the default port anyway, but you can change it here
